spring.application.name=SpringBootDemo2

spring.datasource.url=jdbc:sqlserver://host.docker.internal:1433;databaseName=BooksDb;encrypt=true;trustServerCertificate=truespring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=Prod
spring.datasource.password=123456
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServerDialect



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none