spring.application.name=SpringBootDemo2

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=BooksDb;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=Dev
spring.datasource.password=SqlServer@123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none